#!/usr/bin/env node
/**
 * Sidebar Validation Script
 *
 * Ensures all documentation pages are discoverable in the sidebar.
 * Fails the build if any pages are orphaned (not in sidebar config).
 */

import { readFileSync, readdirSync, statSync } from 'fs';
import { join, relative, extname, basename } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');
const DOCS_DIR = join(ROOT, 'src/content/docs');
const CONFIG_FILE = join(ROOT, 'astro.config.mjs');

// Directories that are autogenerated in sidebar
const AUTOGENERATED_DIRS = [
  '1code',
  'artifact-manager-mac',
  'xcloud',
  'cloudflare',
  'supabase',
  'vercel',
  'bcms',
  'wp-manager',
  'bricks-builder-agent',
  'claude-code',
  'claude-new-project',
  'linkshort',
  'env-var-assistant',
  'jb-cloud-app-tracker',
  'jb-cloud-docs',
  'ui-resources',
  'resources',
];

// Pages manually listed in sidebar (slugs without extension)
const MANUAL_PAGES = ['index', 'documentation-workflow', 'changelog'];

/**
 * Recursively get all markdown/mdx files in a directory
 */
function getAllDocFiles(dir, files = []) {
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      getAllDocFiles(fullPath, files);
    } else if (['.md', '.mdx'].includes(extname(entry))) {
      files.push(fullPath);
    }
  }

  return files;
}

/**
 * Check if a file has sidebar.hidden: true in frontmatter
 */
function isHiddenPage(filePath) {
  try {
    const content = readFileSync(filePath, 'utf-8');
    const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);

    if (frontmatterMatch) {
      const frontmatter = frontmatterMatch[1];
      // Check for sidebar.hidden or sidebar: { hidden: true }
      if (
        frontmatter.includes('sidebar:') &&
        (frontmatter.includes('hidden: true') || frontmatter.includes('hidden:true'))
      ) {
        return true;
      }
    }
  } catch {
    // If we can't read the file, assume it's not hidden
  }
  return false;
}

/**
 * Get the slug from a file path (relative to docs dir, without extension)
 */
function getSlug(filePath) {
  const relativePath = relative(DOCS_DIR, filePath);
  const withoutExt = relativePath.replace(/\.(md|mdx)$/, '');
  return withoutExt;
}

/**
 * Check if a file is in an autogenerated directory
 */
function isInAutogeneratedDir(filePath) {
  const relativePath = relative(DOCS_DIR, filePath);
  const parts = relativePath.split('/');

  if (parts.length > 1) {
    return AUTOGENERATED_DIRS.includes(parts[0]);
  }
  return false;
}

/**
 * Check if a file is manually listed in sidebar
 */
function isManuallyListed(filePath) {
  const slug = getSlug(filePath);
  return MANUAL_PAGES.includes(slug);
}

function main() {
  console.log('Validating sidebar configuration...\n');

  const allFiles = getAllDocFiles(DOCS_DIR);
  const orphanedPages = [];

  for (const file of allFiles) {
    const slug = getSlug(file);

    // Skip hidden pages
    if (isHiddenPage(file)) {
      console.log(`  [hidden] ${slug}`);
      continue;
    }

    // Check if page is discoverable
    if (isInAutogeneratedDir(file)) {
      console.log(`  [auto] ${slug}`);
      continue;
    }

    if (isManuallyListed(file)) {
      console.log(`  [manual] ${slug}`);
      continue;
    }

    // Page is orphaned
    orphanedPages.push({ file, slug });
  }

  console.log('');

  if (orphanedPages.length > 0) {
    console.error('ERROR: Found orphaned pages not in sidebar:\n');
    for (const { slug, file } of orphanedPages) {
      console.error(`  - ${slug}`);
      console.error(`    File: ${relative(ROOT, file)}`);
      console.error('');
    }
    console.error('To fix:');
    console.error('  1. Move file to an autogenerated directory (e.g., resources/)');
    console.error('  2. OR add to MANUAL_PAGES in this script');
    console.error('  3. OR add sidebar.hidden: true to frontmatter\n');
    process.exit(1);
  }

  console.log(`All ${allFiles.length} pages are discoverable in the sidebar.\n`);
  process.exit(0);
}

main();
